# Generated by Django 2.0.6 on 2018-06-25 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='images/%m/%d')),
                ('descricao', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='data de publicacao')),
            ],
        ),
        migrations.CreateModel(
            name='Inseto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.Especie')),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.Imagem')),
            ],
        ),
        migrations.AddField(
            model_name='dado',
            name='inseto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.Inseto'),
        ),
    ]
