# Generated by Django 2.0.6 on 2018-07-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trap_image',
            name='image',
            field=models.TextField(),
        ),
    ]
