# Generated by Django 2.0.6 on 2018-07-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0004_auto_20180704_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trap_image',
            name='image',
        ),
        migrations.AddField(
            model_name='trap_image',
            name='_data',
            field=models.TextField(blank=True, db_column='data'),
        ),
    ]
